# Generated by Django 5.0.3 on 2024-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muvichuserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='1', max_length=1),
        ),
    ]
